#!/usr/bin/env python3
"""Review an evidence-only ChatGPT authoring pack ZIP or tree."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from authoring_pack_review import STATUS_EXIT_CODES, cli_summary, review_input, write_review_outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="Authoring pack .zip or extracted tree.")
    parser.add_argument("--preflight", required=True, help="Preflight JSON generated by the prompt-pack helper.")
    parser.add_argument("--output-dir", required=True, help="Directory for validation-report.json and summary.")
    parser.add_argument("--input-kind", choices=("auto", "zip", "tree"), default="auto")
    parser.add_argument("--extract-dir", help="Optional safe extraction directory for passing ZIP input.")
    args = parser.parse_args(argv)

    output_dir = Path(args.output_dir)
    result = review_input(
        Path(args.input),
        Path(args.preflight),
        input_kind=args.input_kind,
        extract_dir=Path(args.extract_dir) if args.extract_dir else None,
    )
    result = write_review_outputs(output_dir, result)
    print(json.dumps(cli_summary(result, output_dir), ensure_ascii=False, sort_keys=True))
    return STATUS_EXIT_CODES[result["status"]]


if __name__ == "__main__":
    raise SystemExit(main())
